name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (FastAPI) checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # أدوات فحص اختيارية
          pip install ruff
      - name: Lint (ruff) 
        run: ruff check . || true
      - name: Smoke import
        run: python - <<'PY'
from fastapi import FastAPI
import importlib
app_mod = importlib.import_module('main')
print('Loaded main.app:', isinstance(getattr(app_mod,'app',None), FastAPI))
PY

  frontend:
    name: Frontend build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install & build
        run: |
          npm ci || npm install
          npm run build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: front-end/dist
